# Generated by Django 3.1.6 on 2021-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='select',
            field=models.IntegerField(default=0),
        ),
    ]
