# Generated by Django 3.1.6 on 2022-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprmr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
