# Generated by Django 3.1.6 on 2022-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprmr', '0002_auto_20220407_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
