# Generated by Django 3.1.6 on 2022-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprmr', '0003_resume_gist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
