# Generated by Django 3.1.6 on 2022-04-08 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprmr', '0006_remove_resume_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
