# Generated by Django 4.0 on 2021-12-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TOKEN', to='RMRapp.signup')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
