# Generated by Django 4.0 on 2021-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0004_alter_applicantprofile_id_alter_recruiterprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APPLICANTRESUME', to='RMRapp.signup')),
            ],
            options={
                'db_table': 'applicant_resume',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('stipend', models.FloatField(blank=True, null=True)),
                ('apply_by', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('who_can_apply', models.TextField(blank=True, null=True)),
                ('perks', models.TextField(blank=True, null=True)),
                ('number_of_openings', models.IntegerField(blank=True, null=True)),
                ('applicant_list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RECRUITERJOB', to='RMRapp.signup')),
            ],
            options={
                'db_table': 'recruiter_job',
            },
        ),
    ]
