# Generated by Django 4.0 on 2021-12-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0005_recruiterprofile_company_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applicant_list',
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ApplicantResumeJobRecruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APPLICANTFKTABLE', to='RMRapp.signup')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JOBFKTABLE', to='RMRapp.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RECRUITERFKTABLE', to='RMRapp.signup')),
            ],
            options={
                'db_table': 'applicant_resume_job_recruiter',
            },
        ),
    ]
