# Generated by Django 4.0 on 2021-12-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0006_rename_recruiter_id_job_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantresumejobrecruiter',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='applicant',
        ),
        migrations.AddField(
            model_name='resume',
            name='applicant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APPLICANTRESUME', to='RMRapp.applicantprofile'),
        ),
    ]
