# Generated by Django 4.0 on 2021-12-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMRapp', '0007_remove_applicantresumejobrecruiter_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='applicant_profile',
        ),
        migrations.AddField(
            model_name='resume',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='APPLICANTRESUME', to='RMRapp.signup'),
        ),
    ]
